# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Cats Love Me
tagline:          'A Jekyll theme'
description:      'and they love Monokai too.'

author:
  name:           'TacoMeemert'
  url:            https://github.com/SugarXD

gems: [jekyll-paginate]
paginate:         5
paginate_path: "page:num"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/SugarXD
