# Site settings
title: CatsLove_Me
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog where I cover diffrent topics in Computing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://catslove.me" # the base hostname & protocol for your site
github_username:  SugarXD

# Build settings
markdown: redcarpet

paginate: 4

author: Your name

gems: [jekyll-paginate]
